eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone:  ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
    hostname: localhost
logging:
  file: housielog.log
  path: d:\\2024
  level:
    org.springframework.web: "debug"
    org.hibernate: "error"
